steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/laravel_k8_app:master.$BUILD_ID', '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/laravel_k8_app:master.$BUILD_ID']
- name: 'gcr.io/cloud-builders/kubectl'
  args:
    - set
    - image
    - deployment
    - laravel-k8-web
    - laravel-k8-web=gcr.io/$PROJECT_ID/laravel_k8_app:master.$BUILD_ID
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
    - 'CLOUDSDK_CONTAINER_CLUSTER=my-cluster'
images:
- 'gcr.io/$PROJECT_ID/laravel_k8_app:master.$BUILD_ID'
